services:
  app:
    build: .
    container_name: chatbot-app
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=chat-history
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
    #volumes:
      #- .:/app
    networks:
      - chatbot-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=chat-history
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot-network

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - chatbot-network
    volumes:
      - ollama:/root/.ollama

volumes:
  postgres_data:
  ollama:

networks:
  chatbot-network:
    driver: bridge 